name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    uses: MiningOrca/macos-achivements-release-workflows/.github/workflows/macos-achievement-release.yml@main
    with:
      script_path: factorio-achievements-patch.sh
      asset_name: factorio-achievements-patch.sh
      label: PATCHING FACTORIO...
    secrets:
      MINING_ORCA_TOKEN: ${{ secrets.MINING_ORCA_TOKEN }}
